Índice

- [Atividades em sala](#Atividades-em-sala)
- [Trabalho pra casa](#Trabalho-pra-casa)

## Atividades em sala

In [50]:
import numpy as np

A = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
a1,a2 = fatoresLU(A)
M = np.matrix([[1,0,0],[(a1*(-1)),1,0],[(a2*(-1)),0,1]])

if(np.linalg.det(M)!=0):
    print("Diferente de zero")

def fatoresLU(A): 
  
    m12 = A[ 2 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ]
    m21 = A[ 3 - 1, 1 - 1 ] / A[ 1 - 1, 1-1 ] 
    
    return m12, m21

    


MA = M*A
print(MA)


Diferente de zero
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [49]:
A = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])

a1,a2 = fatoresLU(A)
M = np.matrix([[1,0,0],[(a1*(-1)),1,0],[(a2*(-1)),0,1]])

print(np.dot(M,b))


[[ 1.33333333  0.          0.        ]
 [-0.44444444  1.33333333  0.        ]
 [-1.77777778  0.          1.33333333]]


## Trabalho pra casa

In [ ]:
Fazer exemplo 1 completo

In [53]:
U = np.array([[3.,(2.),(4.)], [1.,1.,(2.)], [(4.),(3.),(2.)]])
b = np.array([1.,2.,3.])
L = np.zeros([3,3])

print("matriz exemplo")
print(U)

def FatoracaoLU(U,b):
    n = len(U)
    m = n*[0]
    
    for k in range(0,n):
        L[k][k] = 1
        for i in range(k+1,n):
            m=U[i][k]/U[k][k]
            U[i][k] = 0
            L[i][k] = m
            L
            for j in range(k+1,n):
                U[i][j] = U[i][j] - m*U[k][j]
    return L, U
                


FatoracaoLU(U,b)

print("Matriz L")
print(L)
print("        ")
print("Matriz U")
print(U)
print("        ")
print("Multiplicacao de L por U")
LU = np.dot(L,U)
print(LU)


nL = len(L)
y = nL*[0]

nU = len(U)
x = nU*[0]

def solucaoLy(L,b, n):
    y[0] = b[0]/L[0][0]
    for k in range(1,n-1):
        s = 0
        for j in range(k-1,n):
            s = s + L[k][j]*y[j]
        y[k] = (b[k]-s)/L[k][k]   
        
    return y
  
solucaoLy(L,b,nL)

print(" ")
print("Y = ",y)

def solucaoUx(U,y,n):
    x[n-1] = y[n-1]/U[n-1][n-1]
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + U[k][j]*x[j]
        x[k] = (y[k]-s)/U[k][k]                 
    return x  
  
  
solucaoUx(U,y, nU)

print(" ")
print("X = ",x)

matriz exemplo
[[3. 2. 4.]
 [1. 1. 2.]
 [4. 3. 2.]]
Matriz L
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]
        
Matriz U
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -4.        ]]
        
Multiplicacao de L por U
[[3. 2. 4.]
 [1. 1. 2.]
 [4. 3. 2.]]
 
Y =  [1.0, 1.6666666666666667, 0]
 
X =  [-3.0, 5.0, -0.0]
