In [101]:
import numpy as np

M = np.array([[1.,0,0], [1.,1.,0],[4.,0,1.]])
print(M)

m = np.zeros((3,3))

if(np.linalg.det(M)!=0):
    print("Diferente de zero")

m[2-1,1-1] = M[2-1,1-1]/M[1-1,1-1]


M[2-1,1-1] = -0.333333333#m[2-1,1-1]*M[2-1,1-1]

m[3-1,1-1] = M[3-1,1-1]/M[1-1,1-1]

M[3-1,1-1] = -1.333333333#m[3-1,1-1]*M[3-1,1-1]



print(M)
    

    


[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 4.  0.  1.]]
Diferente de zero
[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


In [ ]:
aux = matriz atal * matriz de etrada

In [ ]:
for k in range(0,n-1):
            for i in range(k+1,n):
            

In [102]:
b = np.array([1,2,3])
#M = np.matrix([[3.,2.,4.], [1.,1.,2.],[4.,3.,2.]])

a = np.dot(b,M)
print(a)

[-3.66666666  2.          3.        ]


In [ ]:
#TRABALHO PRA CASA
Fazer exemplo 1 completo