In [5]:
import numpy as np

A = np.matrix([[3.,2.,4.], [1.,1.,2.],[4.,3.,2.]])
print(A)

if(np.linalg.det(a)==0):
        return print("O DETERMINANTE E ZERO")

[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3.  2.]]
