In [0]:
Anotações

troca a linha 1 com a 3
Então ele multiplica pela Matrix identidade

primeiro resolve o lu e identidade

segundo def retorna lu, p, identidada

In [0]:
import numpy as np

A = np.matrix([[3,(-4),1],[1,2,2],[4,0,(-3)]])
b = np.array([9,3,(-2)])


def PivParcialLU(A,b):
    
    print("Matriz A \n",A)
    n = len(A)
    p = []
    
    
    for i in range(0, n):
        p.append(i)
        #p[i] = i
        
    for k in range(0, n-1):
        pv = abs(A[k,k])
        #ptiny("abss",pv)
        r = k
        
        for i in range(k+1, n):            
            if(abs(A[i,k]) > pv):
                pv = abs(A[i,k])
                r = i
        if(pv == 0):
            break
        elif(r != k):
            aux  = p[k]
            #print("pk\n",p[k])
            p[k] = p[r]
            p[r] = aux 
                        
            for j in range(0, n):
                aux    = A[k,j]
                A[k,j] = A[r,j]
                A[r,j] = aux
              
        for i in range(k+1, n):
            m = A[i,k]/A[k,k]
            A[i,k] = m
            for j in range(k+1, n):
                A[i,j] = A[i,j] - (m * A[k,j])
                            
    c = []
    for i in range(n): 
        r   = p[i]
        c.append(b[r])    
    
    #Ly
    y = np.copy(b)
    for i in range(n):
        soma = 0
        for j in range(0, i-1):
            soma = soma + (A[j,i] * y[j])
        y[i]= c[i] - soma

    #Ux
    x = np.zeros(n)
    x[n-1] = b[n-1]/A[n-1, n-1]
    
    for i in range(n-1, -1, -1):
        soma = 0
        
        for j in range(i+1,n):
            soma = soma + A[i,j]*x[j]
        x[i]= (y[i] - soma)/A[i,i]
    
    
    print("\nY = ",y)
    print("\nX = ",x)
    
PivParcialLU(A,b)

Matriz A 
 [[ 3 -4  1]
 [ 1  2  2]
 [ 4  0 -3]]

Y =  [-2  9 -3]

X =  [-1.25 -3.   -1.  ]


In [0]:
A = np.matrix([[3,(-4),1],[1,2,2],[4,0,(-3)]])
b = np.array([9,3,(-2)])

print(np.linalg.solve(A,b))

=(

[ 1. -1.  2.]
